thunderrevolt/freemarket_sample_71c

Gemfile, Gemfile.lock, app/assets/javascripts/users.coffee, app/assets/stylesheets/users.scss, app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/models/category.rb, app/models/image.rb, app/models/product.rb, app/models/user.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20200319100103_create_categories.rb, db/migrate/20200319101002_devise_create_users.rb, db/migrate/20200319102902_add_ancestry_to_category.rb, db/migrate/20200319103301_create_products.rb, db/migrate/20200319104617_create_images.rb, db/schema.rb, test/controllers/users_controller_test.rb, test/fixtures/categories.yml, test/fixtures/images.yml, test/fixtures/products.yml, test/fixtures/users.yml, test/models/category_test.rb, test/models/image_test.rb, test/models/product_test.rb, test/models/user_test.rb
#What
・画像モデルとDB作成
・カテゴリーモデルとDB作成
・商品モデルとDB作成
・ユーザーモデルとDB作成
#Why
カテゴリー機能実装と商品一覧機能実装の為
=> migirate_image_product_category_user

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/header.scss, app/assets/stylesheets/modules/top-body.scss, app/views/products/index.html.haml
トップページの調整
・商品出品ボタン
・色を統一
・その他微調整
マイナーチェンジ
=> view-change

.gitignore, Gemfile, Gemfile.lock, app/controllers/products_controller.rb, app/models/image.rb, app/models/product.rb, app/uploaders/images_uploader.rb, config/routes.rb, db/migrate/20200319103301_create_products.rb
#what
商品投稿実装（prodaucts＿controllerのみ）
追加
gem 'carrierwave'
gem 'mini_magick'
#why
出品機能がないと成り立たないため
=> Puroducts new　２

db/migrate/20200323074403_create_addresses.rb
=> DB_adress1.4

db/migrate/20200323074403_create_addresses.rb
reference>references
マイグレーション出来ないため
=> DB_adress修正

app/assets/stylesheets/modules/header.scss, app/assets/stylesheets/modules/mypage.scss, app/assets/stylesheets/modules/top-body.scss, app/views/users/show.html.haml
ヘッダー部分テンプレート修正
・absolute解除
・boxshadow解除
#Why
多ページでも使用する上で使用しづらいため
=> edit-header

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/login.scss, app/assets/stylesheets/modules/mypage.scss, app/views/devise/sessions/new.html.haml, app/views/users/show.html.haml
・ログインページのfooterとheaderをrenderに変更
・背景画像の変数を設定
・マイページ背景色の調整
全体で色を統一するため
=> edit-productfooter&header

app/assets/stylesheets/modules/login.scss, app/assets/stylesheets/modules/mypage.scss, app/views/shared/_header.html.haml, app/views/shared/_user_side-bar.html.haml, app/views/users/show.html.haml
・ヘッダーのログアウトボタンにログアウト機能実装
・マイページのサイドバーを繰り返し使うためrender化
・背景色の調整
編集する上でログアウト機能が必要
リファクタリング
ビューの調整
=> edit-logout

app/assets/stylesheets/modules/exhibit.scss, app/views/products/new.html.haml
h3にクラス追加
他のページに影響を出してしまっていいたので、クラス指定してあげた。
=> class_h3_fix

Gemfile
#what
seedデプロイするためにgemfileのlisten を移動
#why
seedデプロイするため
=> gemfile-listen

Gemfile
=> gemfile-listen2

README.md, app/assets/javascripts/buies.coffee, app/assets/stylesheets/application.scss, app/assets/stylesheets/buies.scss, app/assets/stylesheets/modules/buy.scss, app/controllers/buies_controller.rb, app/helpers/buies_helper.rb, app/models/image.rb, app/views/buies/index.html.haml, config/routes.rb, test/controllers/buies_controller_test.rb
購入確認の内容ページビュー作成
・購入確認の機能を実装する為に必要
・購入する際に確認し間違えて購入を防ぐ為
=> 【WIP】Product buy view new

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/user_info_registration.scss, app/views/devise/registrations/new.html.haml
新規登録機能
ログインさせるため
https://gyazo.com/55b64a9d35a72e400f2a8c9bfc45fb16
https://gyazo.com/5da210c58fc4bd11a5debdf6b6b18a78
=> [WIP] registration_front

db/migrate/20200325014415_create_cards.rb, db/schema.rb
=> edit-migrate

app/assets/stylesheets/modules/product-show.scss, app/views/products/show.html.haml
ビューの統一の為、ログアウトページに統一
バラバラのデザインを避ける為
=> 商品詳細ページのパンくず　ビュー修正

app/assets/javascripts/categories_box.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/categories.scss, app/assets/stylesheets/modules/category_index.scss, app/controllers/categories_controller.rb, app/helpers/categories_helper.rb, app/views/categories/index.html.haml, app/views/categories/show.html.haml, config/routes.rb, db/schema.rb, test/controllers/categories_controller_test.rb
=> カテゴリー一覧のビュー

app/views/products/index.html.haml
indexページの画像クリックすると、その画像の商品ページへ移動する。
商品購入画面へ移動するため。
=> index_link

app/assets/stylesheets/application.scss
＠importファイルを読みめるよう編集
ｓｃｓｓが反映されないため
=> change-aplicartion-scss

app/models/user.rb
=> validatesUser_nickname

app/assets/javascripts/payjp.js, spec/controllers/creditcards_controller_spec.rb, spec/factories/creditcards.rb, spec/factories/users.rb, spec/models/creditcard_spec.rb, spec/rails_helper.rb
coreditcardのtest
購入機能のバリデートが機能しているか確かめるため
=> creditcard_test

app/assets/stylesheets/modules/exhibit.scss
=> [WIP]product-new-images

app/assets/stylesheets/modules/product-show.scss, app/controllers/comments_controller.rb, app/controllers/products_controller.rb, app/views/products/show.html.haml, config/routes.rb
商品詳細ページのコメント機能実装
直接お客様同士が商品に対して意見を交わす事で使いやすさを向上させる
=> product-comment

app/assets/stylesheets/modules/category_show.scss, app/controllers/categories_controller.rb, app/views/categories/show.html.haml, app/views/shared/_header.html.haml
カテゴリー一覧で商品と結く
カテゴリーで検索して商品を探しやすくする為
=> カテゴリー一覧詳細と商品一覧

app/assets/javascripts/payjp.js, app/controllers/application_controller.rb, app/controllers/comments_controller.rb, app/controllers/creditcards_controller.rb, app/controllers/products_controller.rb, app/controllers/users_controller.rb
before_action定義
ログインしていない状態で入って欲しくないページに、入ろうとするとtopに行くようにするため
=> before_action

app/assets/stylesheets/modules/login.scss, app/views/devise/sessions/new.html.haml
ログインページのfacebookボタンとgoogleボタンにfontawesomeと画像をつけた。
見た目をよくするため
=> edit-button

app/assets/javascripts/product-new.js, app/assets/stylesheets/modules/exhibit.scss, app/assets/stylesheets/modules/product-show.scss, app/uploaders/images_uploader.rb, app/views/products/new.html.haml
=> product-show-new

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/registration.scss
アプリケーションcssのspanタグにinlinbrokさくじょ
cssがうまく反映されないため
=> new-user-span

app/assets/stylesheets/modules/top-body.scss, app/controllers/products_controller.rb, app/views/products/index.html.haml
=> top_view_fix

README.md, app/assets/stylesheets/modules/category_show.scss, app/assets/stylesheets/modules/exhibit.scss, app/assets/stylesheets/modules/product-show.scss, app/controllers/products_controller.rb, app/views/categories/show.html.haml, app/views/products/edit.html.haml, app/views/products/new.html.haml, app/views/products/show.html.haml, app/views/shared/_header.html.haml
=> 商品詳細の下カテゴリーと紐付け＆削除された商品にbackした時のエラー対処

app/assets/javascripts/product-edit.js, app/assets/stylesheets/modules/exhibit.scss, app/views/products/edit.html.haml, app/views/products/new.html.haml
=> product-new-drop-box

app/assets/javascripts/product-edit.js, app/assets/javascripts/product-new.js, app/assets/stylesheets/modules/exhibit.scss, app/views/products/edit.html.haml, app/views/products/new.html.haml
商品説明欄の入力文字数をリアルタイムで取得する機能追加
入力してる文字が現在何文字かを確認できるようにするため
=> product-new-word-length

app/assets/javascripts/product-edit.js, app/assets/javascripts/product-new.js, app/assets/javascripts/product-show.js
=> product-show-img-change

app/assets/stylesheets/modules/product-show.scss, app/views/products/show.html.haml
コメントが何分前に送られたかを確認できるよう修正
時系列をみやすくするため
=> add-comment-time

app/assets/javascripts/product-show.js, app/assets/stylesheets/modules/product-show.scss, app/views/layouts/application.html.haml, app/views/products/show.html.haml
メイン画像をクリックすると大きくなるよう修正
商品を拡大して細かくみることができ吟味できる
=> show-image-zoom

app/assets/javascripts/product-show.js
商品写真ズームの説明をコメントアウト
正しく表示されなかったため
=> [WIP]show-image-zoom

app/views/products/show.html.haml, db/schema.rb
拡大表示画像のhamlコードを変更
コントローラーで記述していた変数が変更されたため
=> product-show-image2

app/assets/stylesheets/modules/favorites.scss, app/views/favorites/index.html.haml
いいね機能のviewが崩れていたので修正
見た目が悪くなるため
=> いいね機能のview修正

app/assets/stylesheets/modules/category_show.scss, app/assets/stylesheets/modules/product-show.scss, app/assets/stylesheets/modules/variable.scss, app/controllers/products_controller.rb, app/views/products/show.html.haml
・商品詳細の内容の修正
・商品編集のエラーハンドリング
・商品詳細の内容が分かりにく為ビューの調整
・商品編集でrenderだとエラーになる為link_toに変更
=> Category fix

db/migrate/20200408142857_remove_description_from_products.rb, db/migrate/20200408143513_add_description_to_products.rb, db/schema.rb, spec/models/product_spec.rb
商品出品の説明蘭の文字数を1000文字まで入力できるよう修正
エラーが出るため
=> change-product-clumm-description
